spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/auth-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080
  servlet:
    context-path: /auth

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  expiration: 86400 # 1 day in seconds
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  verify-email:
    expiration: 604800 # 7 days in seconds
    secretKey: pHuID1+T84ITaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  x-internal-token: k118wSpPDIVURys

frontend:
  url: http://localhost:3000

