spring:
  application:
    name: delivery-service
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: 27017
      database: delivery-service
      username: root
      password: root
      authentication-database: admin
  datasource:
    url: jdbc:h2:mem:delivery-service
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: delivery-service
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081
  servlet:
    context-path: /delivery
  host_auth_service: ${HOST_AUTH_SERVICE:localhost}
  host_order_service: ${HOST_ORDER_SERVICE:localhost}
  port_auth_service: ${PORT_AUTH_SERVICE:8080}
  port_order_service: ${PORT_ORDER_SERVICE:8083}

logging:
  level:
    org:
      springframework:
        security: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  expiration: 86400 # 1 day in seconds
  secret-key: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  verify-email:
    expiration: 604800 # 7 days in seconds
    secret-key: pHuID1+T84ITaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  x-internal-token: k118wSpPDIVURys

frontend:
  url: http://localhost:3000

open-api:
  url-gateway-localhost: http://localhost:8888/api/v1${server.servlet.context-path}
  url-gateway-radmin: http://26.162.34.110:8888/api/v1${server.servlet.context-path}
  url-localhost: http://localhost:${server.port}${server.servlet.context-path}
  url-radmin: http://26.162.34.110:${server.port}${server.servlet.context-path}
