spring:
  application:
    name: delivery-service
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: 27017
      database: delivery-service
      username: root
      password: root
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: delivery-service
    producer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9094}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081
  servlet:
    context-path: /delivery
  host_auth_service: ${HOST_AUTH_SERVICE:localhost}
  host_order_service: ${HOST_ORDER_SERVICE:localhost}
  port_auth_service: ${PORT_AUTH_SERVICE:8080}
  port_order_service: ${PORT_ORDER_SERVICE:8083}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  expiration: 86400 # 1 day in seconds
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  x-internal-token: k118wSpPDIVURys

frontend:
  url: http://localhost:3000
